name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd front
        npm install

    - name: Build project
      run: |
        cd front
        npm run build
      env:
        NEXT_PUBLIC_BACK_API: ${{ secrets.BACK_API || 'http://localhost' }}
        NEXT_PUBLIC_PORT: ${{ secrets.PORT || '3001' }}
        NEXT_PUBLIC_ROUTE: ${{ secrets.ROUTE || 'api' }}
